version: '3'

services:
    arbitrum-node:
        container_name: arbitrum
        image: 'offchainlabs/nitro-node:v2.0.8-5b9fe9c'
        restart: always
        stop_grace_period: 30s
        volumes:
            - /arbitrum-node/data/:/arbitrum-node/data/
        ports:
            - "127.0.0.1:8547:8547"
            - "8548:8548"
        command:
        - --init.url=file:/home/user/.arbitrum/nitro/Arbitrum.tar.lz4 
        - --persistent.chain=/arbitrum-node/data/
        - --persistent.global-config=/arbitrum-node/
        - --l1.url=$L1URL
        - --l2.chain-id=42161 
        - --http.api=net,web3,eth,debug 
        - --http.corsdomain=* 
        - --http.addr=0.0.0.0 
        - --http.vhosts=*
        - --graphql.enable
        - --graphql.vhosts=*
        logging:
          driver: json-file
          options:
            max-size: 10m
            max-file: "10"
        env_file:
          - $PWD/.env