version: '3'

services:
    arbitrum-node:
        container_name: arbitrum
        image: 'offchainlabs/nitro-node:v2.0.8-5b9fe9c'
        restart: always
        stop_grace_period: 30s
        volumes:
            - '/arbitrum/data/:/arbitrum-node/data/'	
        ports:
            - '8547:8547'
            - '8548:8548'
        command:
        - --init.url="https://snapshot.arbitrum.io/mainnet/nitro.tar"
        - --persistent.chain=/arbitrum-node/data/
        - --persistent.global-config=/arbitrum-node/
        - --l1.url= "$L1URL"
        - --l2.chain-id=42161 
        - --http.api=net,web3,eth,debug 
        - --http.corsdomain=* 
        - --http.addr=0.0.0.0 
        - --http.vhosts=*
        logging:
          driver: json-file
          options:
            max-size: 10m
            max-file: "10"
        env_file:
          - $PWD/.env