version: '3'

services:
  #
  # Ethereum mainnet geth
  #
  # https://hub.docker.com/r/ethereum/client-go
  # https://github.com/Capgemini-AIE/ethereum-docker/blob/master/docker-compose-standalone.yml
  #
  ethereum:
    image: ethereum/client-go:v1.10.6
    restart: always
    container_name: ethereum
    ipc: shareable
    command: --http --http.addr 0.0.0.0 --cache 8000 --syncmode snap --graphql --ipcpath=/root/ipc/ethereum.ipc
    volumes:
      - ./data/ethereum:/root/.ethereum
      - ./ipc:/root/ipc
    ports:
      - "127.0.0.1:8545:8545" # HTTP
      - "30303:30303" # p2p
      - "30303:30303/udp" # p2p
